ECC/Controllers/ResistorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ECC.Core.Enums;
using ECC.Models;
using ECC.Core.Interfaces;

namespace ECC.Controllers
{
    public class ResistorController : Controller
    {
        private IOhmValueCalculator _resistorCal;
        public ResistorController(IOhmValueCalculator resistorCal)
        {
            _resistorCal = resistorCal;
        }

        public ActionResult Index()
        {
            var model = new ResistorViewModels();
            model.ComponentValues = GetSelectListItems();
            model.TolenranceValues = GetToleranceSelectListItem();

            return View(model);
        }

        [HttpPost]
        public ActionResult Index(ResistorViewModels model)
        {
            var realValue = _resistorCal.RealCalculateOhmValue(model.BandA.ToString(), model.BandB.ToString(), model.BandC.ToString(), model.BandD.ToString());
            model.ComponentValues = GetSelectListItems();
            model.TolenranceValues = GetToleranceSelectListItem();

            if (ModelState.IsValid)
            {
                model.ResistorValue = _resistorCal.CalculateOhmValue(model.BandA.ToString(), model.BandB.ToString(), model.BandC.ToString());
                model.ResistorMinValue = realValue.Item1;
                model.ResistorMaxValue = realValue.Item2;
            }


            return View(model);
        }

        private IEnumerable<SelectListItem> GetToleranceSelectListItem()
        {
            var selectList = new List<SelectListItem>();

            var enumValues = Enum.GetValues(typeof(ColorEnum)) as ColorEnum[];
            if (enumValues == null)
                return null;

            foreach (var enumValue in enumValues)
            {
                if ((int)enumValue < 0)
                {
                    selectList.Add(new SelectListItem
                    {
                        Value = enumValue.ToString(),
                        Text = enumValue.ToString()
                    });
                }

            }

            return selectList;
        }


        private IEnumerable<SelectListItem> GetSelectListItems()
        {
            var selectList = new List<SelectListItem>();

            var enumValues = Enum.GetValues(typeof(ColorEnum)) as ColorEnum[];
            if (enumValues == null)
                return null;

            foreach (var enumValue in enumValues)
            {
                if ((int)enumValue >= 0)
                {
                    selectList.Add(new SelectListItem
                    {
                        Value = enumValue.ToString(),
                        Text = enumValue.ToString()
                    });
                }
            }

            return selectList;
        }
    }
}

ECC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Resistor", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>